# Configuración de H2
spring.datasource.url=jdbc:h2:mem:ecommerce_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para poder entrar a la consola de H2 en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate: Crear tablas automáticamente y mostrar SQL en consola
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
